name: publish

on:
  release:
    types: [published]

jobs:
  build-and-push-image-api:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/api.dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-rome-api:latest
            ghcr.io/markrdavison/markdavison-rome-api:${{ github.event.release.tag_name }}
            
  build-and-push-image-bff-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/bff-web.dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-rome-bff-web:latest
            ghcr.io/markrdavison/markdavison-rome-bff-web:${{ github.event.release.tag_name }}

  build-and-push-image-web:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      
        
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.MRD_GITHUB_PAT }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          file: ./Docker/web.dockerfile
          context: ./src
          push: true
          tags: |
            ghcr.io/markrdavison/markdavison-rome-web:latest
            ghcr.io/markrdavison/markdavison-rome-web:${{ github.event.release.tag_name }}